"""empty message

Revision ID: 9ef948a0641e
Revises: 
Create Date: 2022-11-27 16:30:07.757243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef948a0641e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apt_deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bjdcode', sa.String(length=10), nullable=True),
    sa.Column('bjdong', sa.String(length=10), nullable=False),
    sa.Column('apartment', sa.String(length=100), nullable=False),
    sa.Column('buildyear', sa.String(length=10), nullable=False),
    sa.Column('dealyear', sa.String(length=10), nullable=False),
    sa.Column('dealmonth', sa.String(length=10), nullable=False),
    sa.Column('dealday', sa.String(length=10), nullable=False),
    sa.Column('area', sa.String(length=10), nullable=False),
    sa.Column('floor', sa.String(length=10), nullable=False),
    sa.Column('price', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bjd_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('si', sa.String(length=10), nullable=True),
    sa.Column('gu', sa.String(length=10), nullable=True),
    sa.Column('dong', sa.String(length=10), nullable=False),
    sa.Column('bjdcode', sa.String(length=20), nullable=False),
    sa.Column('apartment', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bjd_code')
    op.drop_table('apt_deal')
    # ### end Alembic commands ###
